version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=3000'
    image: 'fanney13/tictactoe'
    build: 
        context: '.'
        dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
  postgres:
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: 'postgres'
    ports:
      - "5432:5432"